import type { Metadata } from 'next'
import { Inter, Dancing_Script, Montserrat } from 'next/font/google'
import './globals.css'
import { Theme } from '@radix-ui/themes'
import '@radix-ui/themes/styles.css';

const base = Montserrat({ subsets: ['latin'] })
const dancing = Dancing_Script({ subsets: ['latin'], variable: '--script' })

export const metadata: Metadata = {
  title: 'Info Card Studio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${base.className} ${dancing.variable} dark bg-gradient-to-b from-zinc-950 to-zinc-800`}>
        <Theme>
          {children}
        </Theme>
      </body>
    </html>
  )
}
